# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
Z = np.zeros(10)
print(Z)

#### 4.  How to find the memory size of any array (★☆☆)

In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
Z.size

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
z = np.zeros(10)
z[4] = 1
print(z)
# [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Z = np.arange(10,50)
print(Z)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = np.arange(51)
Z = Z[::-1]
print(Z)


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
Z = np.arange(12).reshape(4,3)
print(Z)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
nz = np.nonzero([1,2,0,4,0,0,5])
print(nz)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
Z = np.eye(5,k=1)
print(Z)
z2 = np.eye(5,k=-1,dtype=int)
print(z2)
86.8*5.37/16.9

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
Z = np.random.random((3,3,3))
print(Z)
# np.info(np.random.random)
# [[[0.63993842 0.48101524 0.63524939]
#   [0.18740333 0.35754501 0.81010404]
#   [0.68114606 0.90593805 0.67591743]]

#  [[0.39021348 0.94964045 0.6448069 ]
#   [0.04099252 0.56486972 0.80860247]
#   [0.46281475 0.74650415 0.74251358]]

#  [[0.6665822  0.76134665 0.09081488]
#   [0.68041434 0.93412739 0.01955354]
#   [0.01488111 0.90064339 0.41344118]]]
z = 5 * np.random.random((3, 3, 3)) - 5
print(z)
# [[[-0.54155421 -2.51497393 -4.10428815]
#   [-4.96758279 -3.19414567 -3.62450707]
#   [-2.17001487 -3.84169024 -3.87450898]]

#  [[-3.47144518 -1.67246788 -3.59526373]
#   [-3.50986099 -0.41808582 -4.16107977]
#   [-3.1543739  -4.25956866 -1.88502055]]

#  [[-1.5100815  -1.23981664 -4.45815056]
#   [-2.08542009 -3.42167315 -2.10173514]
#   [-1.51822203 -3.94119277 -0.25185589]]]
print(z.max(),z.min())
# [[[-3.88303978 -3.20624247 -4.47015713]
#   [-4.38047721 -3.94420709 -1.46800251]
#   [-3.42411886 -3.2418648  -1.45189343]]

#  [[-4.72402221 -1.45965983 -3.3392552 ]
#   [-2.70079311 -3.44727761 -0.73690442]
#   [-2.60529665 -4.53730684 -3.37070446]]

#  [[-1.98866669 -1.97194627 -0.42284383]
#   [-0.09383499 -3.73258462 -4.36860107]
#   [-0.1850216  -4.26937024 -0.36835503]]]
# -0.09383498623129505 -4.724022211720695

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print(z.max(),z.min())

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(Z, '/t/',m)
# [0.80987896 0.419412   0.42411804 0.25321376 0.01129237 0.50292676
#  0.58852011 0.56933458 0.34181259 0.7849266  0.30678997 0.0819499
#  0.44834937 0.38943059 0.68510589 0.47078087 0.56098448 0.75629656
#  0.1015044  0.52618279 0.10670109 0.03502625 0.35051387 0.98029132
#  0.55794295 0.12086003 0.51343374 0.69730783 0.1279773  0.20142955] 
# 0.4241431501973716

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z, np.info(np.ones))
# [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

np.ones(5)
# array([ 1.,  1.,  1.,  1.,  1.])

np.ones((5,), dtype=int)
# array([1, 1, 1, 1, 1])

np.ones((2, 1))
# array([[ 1.],
#        [ 1.]])

s = (2,2)
np.ones(s)
# array([[ 1.,  1.],
#        [ 1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
np.info(np.pad)
# [[0. 0. 0. 0. 0. 0. 0.]
#  [0. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 0.]
#  [0. 1. 1. 1. 1. 1. 0.]
#  [0. 0. 0. 0. 0. 0. 0.]]

a = [1, 2, 3, 4, 5]
np.pad(a, (2,3), 'constant', constant_values=(4, 6)) # 指定常量填充
# array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

np.pad(a, (2, 3), 'edge')  # 使用边界值填充
# array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

np.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4)) # 指定结束值，按线性坡度取值填充
# array([ 5,  3,  1,  2,  3,  4,  5,  2, -1, -4])

np.pad(a, (2,), 'maximum') # 取最大值填充，左右均填充2个
# array([5, 5, 1, 2, 3, 4, 5, 5, 5])

np.pad(a, (2,), 'mean') # 取均值填充
# array([3, 3, 1, 2, 3, 4, 5, 3, 3])

np.pad(a, (2,), 'median') # 取中位数填充
# array([3, 3, 1, 2, 3, 4, 5, 3, 3])

np.pad(a, (2, 3), 'reflect') # 以边界值为轴，进行镜像填充（镜像不包含边界值）
# array([3, 2, 1, 2, 3, 4, 5, 4, 3, 2])

np.pad(a, (2, 3), 'reflect', reflect_type='odd') # 以边界值为轴，再以边界值的2倍减去镜像值进行填充
# array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

np.pad(a, (2, 3), 'symmetric')  # 以数组边缘为轴，进行镜像填充（镜像包含边界值）
# array([2, 1, 1, 2, 3, 4, 5, 5, 4, 3])

np.pad(a, (2, 3), 'symmetric', reflect_type='odd') # 以数组边缘为轴，再以边界值的2倍减去镜像值进行填充
# array([0, 1, 1, 2, 3, 4, 5, 5, 6, 7])

np.pad(a, (2, 3), 'wrap') # 前从后、后从前复制值进行填充
# array([4, 5, 1, 2, 3, 4, 5, 1, 2, 3])

a = [[1, 2], [3, 4]]
np.pad(a, ((3, 2), (2, 3)), 'minimum') # 取最小值填充，填充上3下2、左2右3
# array([[1, 1, 1, 2, 1, 1, 1],
#        [1, 1, 1, 2, 1, 1, 1],
#        [1, 1, 1, 2, 1, 1, 1],
#        [1, 1, 1, 2, 1, 1, 1],
#        [3, 3, 3, 4, 3, 3, 3],
#        [1, 1, 1, 2, 1, 1, 1],
#        [1, 1, 1, 2, 1, 1, 1]])

def pad_with(vector, pad_width, iaxis, kwargs):
    pad_value = kwargs.get('padder', 10)
    vector[:pad_width[0]] = pad_value
    vector[-pad_width[1]:] = pad_value
    return vector
a = np.arange(6)
a = a.reshape((2, 3))
np.pad(a, 2, pad_with) # 自定义函数规则进行填充
# array([[10, 10, 10, 10, 10, 10, 10],
#        [10, 10, 10, 10, 10, 10, 10],
#        [10, 10,  0,  1,  2, 10, 10],
#        [10, 10,  3,  4,  5, 10, 10],
#        [10, 10, 10, 10, 10, 10, 10],
#        [10, 10, 10, 10, 10, 10, 10]])
np.pad(a, 2, pad_with, padder=100)
# array([[100, 100, 100, 100, 100, 100, 100],
#        [100, 100, 100, 100, 100, 100, 100],
#        [100, 100,   0,   1,   2, 100, 100],
#        [100, 100,   3,   4,   5, 100, 100],
#        [100, 100, 100, 100, 100, 100, 100],
#        [100, 100, 100, 100, 100, 100, 100]])

#### 17. What is the result of the following expression? (★☆☆)

In [ ]:
print(np.nan * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

z = np.arange(5,dtype=float)
z[4] = np.nan
print(z)
# z[z!=z]=0
z[np.isnan(z)]=0
print(z)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z,np.info(np.diag))
# [[0 0 0 0 0]
#  [1 0 0 0 0]
#  [0 2 0 0 0]
#  [0 0 3 0 0]
#  [0 0 0 4 0]]
x = np.arange(9).reshape((3,3))
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

np.diag(x)
# array([0, 4, 8])
np.diag(x, k=1)
# array([1, 5])
np.diag(x, k=-1)
# array([3, 7])
np.diag(np.diag(x))
# array([[0, 0, 0],
#        [0, 4, 0],
#        [0, 0, 8]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)
# [[0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]]

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8)))
# (1, 5, 4)  # 第2层6行第4列（1*（7*8）+ 5*8 + 4 == 100）
np.unravel_index([22, 41, 37], (7,6)) # 默认以行主（C样式）顺序编制索引
# (array([3, 6, 6]), array([4, 5, 1]))  # 第4行第5列（3*6 + 4 == 22），第7行第6列（6*6 + 5 == 41），第7行第2列（6*6 + 1 == 37）
np.unravel_index([31, 41, 13], (7,6), order='F') # 以列主（Fortran样式）顺序编制索引
# (array([3, 6, 6]), array([4, 5, 1]))  # 第4行第5列（3*6 + 4 == 31），第7行第6列（6*6 + 5 == 41），第7行第2列（6*6 + 1 == 13）
np.unravel_index(1621, (6,7,8,9))
# (3, 1, 4, 1)  # 第1维（1621/(7*8*9)=3）、第2维(1621-3*7*8*9)/(8*9)=1、第3维(1621-3*7*8*9-1*8*9)/9=4、第4维(1621-3*7*8*9-1*8*9-4*9)=1

print(np.arange(42).reshape((7,6)))
# [[ 0  1  2  3  4  5]
#  [ 6  7  8  9 10 11]
#  [12 13 14 15 16 17]
#  [18 19 20 21 22 23]
#  [24 25 26 27 28 29]
#  [30 31 32 33 34 35]
#  [36 37 38 39 40 41]]

print(np.arange(42).reshape((6,7)).transpose()) # 行列转换
# [[ 0  7 14 21 28 35]
#  [ 1  8 15 22 29 36]
#  [ 2  9 16 23 30 37]
#  [ 3 10 17 24 31 38]
#  [ 4 11 18 25 32 39]
#  [ 5 12 19 26 33 40]
#  [ 6 13 20 27 34 41]]

print(np.unravel_index(22,(7,6)), np.unravel_index(41,(7,6)), np.unravel_index(37,(7,6)))
# (3, 4) (6, 5) (6, 1)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z, np.info(np.tile))

a = np.array([0, 1, 2])
np.tile(a, 2)
# array([0, 1, 2, 0, 1, 2])
np.tile(a, (2, 2))
# array([[0, 1, 2, 0, 1, 2],
#        [0, 1, 2, 0, 1, 2]])
np.tile(a, (2, 1, 2))
# array([[[0, 1, 2, 0, 1, 2]],
#        [[0, 1, 2, 0, 1, 2]]])
np.tile(a, (2, 1, 1))
# array([[[0, 1, 2]],
#        [[0, 1, 2]]])
np.tile(a, (2, 2, 1))
# array([[[0, 1, 2],
#         [0, 1, 2]],
#        [[0, 1, 2],
#         [0, 1, 2]]])

b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)
# array([[1, 2, 1, 2],
#        [3, 4, 3, 4]])
np.tile(b, (2, 1))
# array([[1, 2],
#        [3, 4],
#        [1, 2],
#        [3, 4]])

c = np.array([1,2,3,4])
np.tile(c,(4,1))
# array([[1, 2, 3, 4],
#        [1, 2, 3, 4],
#        [1, 2, 3, 4],
#        [1, 2, 3, 4]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)
# [[0.63666786 0.46159627 0.3922908  0.95998631 0.50312812]
#  [0.54844247 0.16826243 0.16538416 0.68621378 0.76763629]
#  [0.63517766 0.66725313 0.14872901 0.97257321 0.8510858 ]
#  [0.92260227 0.80335286 0.00594323 0.68313496 0.9695426 ]
#  [0.39614766 0.47606303 0.46442819 0.69499545 0.86854569]]
# [[ 0.15805527 -0.4899692  -0.74650221  1.35481294 -0.33623976]
#  [-0.1685095  -1.57573933 -1.58639319  0.34144864  0.64283268]
#  [ 0.15253935  0.27126612 -1.64804197  1.40140315  0.95171958]
#  [ 1.21643656  0.77503694 -2.17656107  0.33005244  1.39018537]
#  [-0.73222608 -0.43642074 -0.47948689  0.37395384  1.01634705]]

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
# print(np.info(np.dtype))
np.array((255,255,255,1),dtype=color)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(np.ones((5,3)))
print(np.ones((3,2)))
print(Z)
print(np.info(np.dot))
# Alternative solution, in Python 3.5 and above
# Z = np.ones((5,3)) @ np.ones((3,2))

# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]
# [[3. 3.]
#  [3. 3.]
#  [3. 3.]
#  [3. 3.]
#  [3. 3.]]

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)
# [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]

#### 26. What is the output of the following script? (★☆☆)

In [ ]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
np.info(sum)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [ ]:
Z = np.array([4,nan])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)
Z/1/1

#### 28. What are the result of the following expressions?

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# Author: Charles R Harris

Z = np.random.uniform(10,9,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))
# [ 5.69216015 -0.37467005  8.81260684 -6.83084083 -9.89740496 -0.39031315
#  -8.83141291 -5.79863017 -9.0514372   6.26528328]
# [  6.  -1.   9.  -7. -10.  -1.  -9.  -6. -10.   7.]
print(np.info(np.random.uniform),np.info(np.abs),np.info(np.ceil),np.info(np.copysign))


In [ ]:
import matplotlib.pyplot as plt
N = 8
y = np.zeros(N)
x1 = np.linspace(0, 10, N, endpoint=True)
x2 = np.linspace(0, 10, N, endpoint=False)
print(x1)
print(x2)
plt.plot(x1, y, 'o')
plt.plot(x2, y + 0.5, 'o')
plt.ylim([-0.5, 1])
plt.show()


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))
# [7 4 9 9 8 6 6 0 2 9]
# [1 6 3 5 2 5 7 0 5 3]
# [0 2 6 7]
help(np.intersect1d)

from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
# array([3])

x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
print(x_ind, y_ind)
# (array([0, 2, 4]), array([1, 0, 2]))
print(xy, x[x_ind], y[y_ind])
# (array([1, 2, 4]), array([1, 2, 4]), array([1, 2, 4]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

np.sqrt([1,4,9])
# array([ 1.,  2.,  3.])
np.sqrt([4, -1, -3+4J])
# array([ 2.+0.j,  0.+1.j,  1.+2.j])
np.sqrt([4, -1, np.inf])
# array([  2.,  NaN,  Inf])

np.lib.scimath.sqrt(-1) == np.emath.sqrt(-1)
# True
np.lib.scimath.sqrt(1)
# 1.0
np.lib.scimath.sqrt([1, 4])
# array([ 1.,  2.])
np.lib.scimath.sqrt([-1,4])
# array([ 0.+1.j,  2.+0.j])

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)
# 2019-02-11 2019-02-12 2019-02-13

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2019-02-02', '2019-03-15', dtype='datetime64[D]')
print(Z)
# ['2019-02-02' '2019-02-03' '2019-02-04' '2019-02-05' '2019-02-06'
#  '2019-02-07' '2019-02-08' '2019-02-09' '2019-02-10' '2019-02-11'
#  '2019-02-12' '2019-02-13' '2019-02-14' '2019-02-15' '2019-02-16'
#  '2019-02-17' '2019-02-18' '2019-02-19' '2019-02-20' '2019-02-21'
#  '2019-02-22' '2019-02-23' '2019-02-24' '2019-02-25' '2019-02-26'
#  '2019-02-27' '2019-02-28' '2019-03-01' '2019-03-02' '2019-03-03'
#  '2019-03-04' '2019-03-05' '2019-03-06' '2019-03-07' '2019-03-08'
#  '2019-03-09' '2019-03-10' '2019-03-11' '2019-03-12' '2019-03-13'
#  '2019-03-14']

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
np.multiply(2.0, 4.0)
# 8.0

x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)
# array([[  0.,   1.,   4.],
#        [  0.,   4.,  10.],
#        [  0.,   7.,  16.]])

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A)
print(B)
# [1. 1. 1.]
# [2. 2. 2.]
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
# array([-1.5, -1.5, -1.5])
np.info(np.multiply)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [147]:
z = np.random.uniform(-10,10,10)
print(z)
print(z - z%1)  # 减去余数
print(np.floor(z))  # 使用向下取整
print(np.ceil(z)-1)  # 使用向上取整，再减去1
print(z.astype(int))  # 使用类型转换，直接转成整数，正数向下取整，负数向上取整（靠近0）
print(np.trunc(z))  # 使用trunc方法正数向下取整，负数向上取整（靠近0）
print(np.sign(z) * np.ceil(np.abs(z)))  # 正数向上取整，负数向下取整（远离0）
# [ 9.26371331 -3.7803969   3.07408863 -6.27843261 -1.23193169  4.76489736
#   3.88857568 -3.77606056  1.96998956 -2.22430459]
# [ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
# [ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
# [ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
# [ 9 -3  3 -6 -1  4  3 -3  1 -2]
# [ 9. -3.  3. -6. -1.  4.  3. -3.  1. -2.]
# [10. -4.  4. -7. -2.  5.  4. -4.  2. -3.]

[ 9.26371331 -3.7803969   3.07408863 -6.27843261 -1.23193169  4.76489736
  3.88857568 -3.77606056  1.96998956 -2.22430459]
[ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
[ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
[ 9. -4.  3. -7. -2.  4.  3. -4.  1. -3.]
[ 9 -3  3 -6 -1  4  3 -3  1 -2]
[ 9. -3.  3. -6. -1.  4.  3. -3.  1. -2.]
[10. -4.  4. -7. -2.  5.  4. -4.  2. -3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [149]:
z = np.zeros((5,5))
print(z)
z += np.arange(5)
print(z)
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]
# [[0. 1. 2. 3. 4.]
#  [0. 1. 2. 3. 4.]
#  [0. 1. 2. 3. 4.]
#  [0. 1. 2. 3. 4.]
#  [0. 1. 2. 3. 4.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [151]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
np.info(np.fromiter)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
fromiter(iterable, dtype, count=-1)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
>>> iterable = (x*x for x in range(5))
>>> np.fromiter(iterable, float)
array([  0.,   1.,   4.,   9.,  16.])


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [152]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [154]:
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)
# [0.88228329 0.08281638 0.41213483 0.65500255 0.46553488 0.58674927
#  0.9413287  0.25007143 0.32588758 0.42595198]
# [0.08281638 0.25007143 0.32588758 0.41213483 0.42595198 0.46553488
#  0.58674927 0.65500255 0.88228329 0.9413287 ]

[0.88228329 0.08281638 0.41213483 0.65500255 0.46553488 0.58674927
 0.9413287  0.25007143 0.32588758 0.42595198]
[0.08281638 0.25007143 0.32588758 0.41213483 0.42595198 0.46553488
 0.58674927 0.65500255 0.88228329 0.9413287 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [161]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.multiply.reduce([2,3,5])
# 30
X = np.arange(8).reshape((2,2,2))
# array([[[0, 1],
#         [2, 3]],
#        [[4, 5],
#         [6, 7]]])
np.add.reduce(X, 0)
# array([[ 4,  6],
#        [ 8, 10]])
np.add.reduce(X) # confirm: default axis value is 0
# array([[ 4,  6],
#        [ 8, 10]])
np.add.reduce(X, 1)
# array([[ 2,  4],
#        [10, 12]])
np.add.reduce(X, 2)
# array([[ 1,  5],
#        [ 9, 13]])
np.add.reduce([10], initial=5)
# 15
np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initializer=10)
# array([14., 14.])

np.minimum.reduce([], initial=np.inf)
# inf
np.minimum.reduce([])
# Traceback (most recent call last):
#     ...
# ValueError: zero-size array to reduction operation minimum which has no identity

In [160]:
# Author: Evgeni Burovski

Z = np.arange(10)
print(np.add.reduce(Z), np.sum(Z))
# %timeit np.add.reduce(Z)
# %timeit np.sum(Z)
# 45 45
# 1.31 µs ± 92.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
# 3.06 µs ± 771 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
np.info(np.add.reduce)

45 45
reduce(a, axis=0, dtype=None, out=None, keepdims=False, initial)

Reduces `a`'s dimension by one, by applying ufunc along one axis.

Let :math:`a.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then
:math:`ufunc.reduce(a, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =
the result of iterating `j` over :math:`range(N_i)`, cumulatively applying
ufunc to each :math:`a[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.
For a one-dimensional array, reduce produces results equivalent to:
::

 r = op.identity # op = ufunc
 for i in range(len(A)):
   r = op(r, A[i])
 return r

For example, add.reduce() is equivalent to sum().

Parameters
----------
a : array_like
    The array to act on.
axis : None or int or tuple of ints, optional
    Axis or axes along which a reduction is performed.
    The default (`axis` = 0) is perform a reduction over the first
    dimension of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0



#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
# np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

#### 54. How to read the following file? (★★☆)

In [ ]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [ ]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [ ]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
# Author: Ryan G.

x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)